all: amortised.pdf AlwaysResizeQueue.pdf

versionid:
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\\gdef\\GITAbrHash{%h}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" >> vc.tex

amortised.pdf: amortised.tex versionid
	pdflatex amortised

AlwaysResizeQueue.pdf: AlwaysResizeQueue.tex versionid
	pdflatex AlwaysResizeQueue
